DATASET: 'scannet'
BATCH_SIZE: 1
SAVE_SCENE_MESH: True
SAVE_SCENE_MESH_ITER: False
LOGDIR: './checkpoints/test_model'
SAVE_FREQ: 1
MODE: 'test'

TRAIN:
  PATH: '../data/DATAROOT_SCANNET/scannet'
  #PATH: '/scannet/DATAROOT_SCANNET/scannet'
  EPOCHS: 991
  N_VIEWS: 9
  LR: 1e-3
  N_WORKERS: 8
  LREPOCHS: '12,24,48:2'

TEST:
  PATH: '../data/DATAROOT_SCANNET/scannet'
  #PATH: '/scannet/DATAROOT_SCANNET/scannet'
  N_VIEWS: 9
  N_WORKERS: 4

MODEL:
  N_LAYER: 3
  #N_VOX: [96, 96, 96]
  VOXEL_SIZE: 0.04
  TRAIN_NUM_SAMPLE: [4096, 16384, 65536]
  TEST_NUM_SAMPLE: [4096, 16384, 65536]

  BACKBONE2D:
    ARC: 'fpn-mnas-1'

  FUSION:
    FUSION_ON: True
    HIDDEN_DIM: 64

    AVERAGE: False
    FULL: True

  RERENDER:
    LOSS: True
    WEIGHT: 5
    MAX_NUM_POINTS: 1000000
    RAYCAST_DEPTH_MAX: 15

  PROJECTION:
    LOSS: False
    LOSS_WEIGHT: 10
    THRESHOLD: 0.3
    UPSCALE: 5
    
  FOV_TSDF_LOSS:
    LOSS: False
    WEIGHT: 10
    DEPTH_INDEX_MAX: 192

  LW: [1.0, 1.0, 1.0, 1.0, 0.8, 0.64]

  THRESHOLDS: [0, 0, 0]
  POS_WEIGHT: 1.5
