DATASET: 'scannet'
BATCH_SIZE: 1
SAVE_SCENE_MESH: False
LOGDIR: './checkpoints'
SAVE_FREQ: 1
SUMMARY_FREQ: 20
MODE: 'train'
LOADCKPT: './checkpoints/08-19-03-40(original_part_1)/model_000020.ckpt'
# LOADCKPT: './checkpoints/08-20-13-03(original_part_2)/model_000035.ckpt'
# LOADCKPT: './checkpoints/08-27-19-34/model_000018.ckpt'

TRAIN:
  PATH: '../data/DATAROOT_SCANNET/scannet'
  #PATH: '/scannet/DATAROOT_SCANNET/scannet'
  EPOCHS: 991
  N_VIEWS: 9
  LR: 1e-3
  N_WORKERS: 8
  LREPOCHS: '12,24,36,48:2'
  APPLY_LOSS: 20

TEST:
  PATH: '../data/DATAROOT_SCANNET/scannet'
  #PATH: '/scannet/DATAROOT_SCANNET/scannet'
  N_VIEWS: 9
  N_WORKERS: 4

MODEL:
  N_LAYER: 3
  N_VOX: [96, 96, 96]
  VOXEL_SIZE: 0.04
  TRAIN_NUM_SAMPLE: [4096, 16384, 65536]
  TEST_NUM_SAMPLE: [4096, 16384, 65536]

  BACKBONE2D:
    ARC: 'fpn-mnas-1'

  FUSION:
    FUSION_ON: True
    HIDDEN_DIM: 64

    AVERAGE: False
    FULL: True

  RERENDER:
    LOSS: True
    WEIGHT: 1
    MAX_NUM_POINTS: 1000000
    RAYCAST_DEPTH_MAX: 3

  PROJECTION:
    LOSS: False
    LOSS_WEIGHT: 10
    THRESHOLD: 0.3
    UPSCALE: 5
    
  FOV_TSDF_LOSS:
    LOSS: False
    WEIGHT: 10
    DEPTH_INDEX_MAX: 192

  LW: [1.0, 0.8, 0.64]

  THRESHOLDS: [0.5, 0.5, 0.5]
  POS_WEIGHT: 1.5