DATASET: 'scannet'
BATCH_SIZE: 1
SAVE_SCENE_MESH: False
LOGDIR: './checkpoints'
# LOGDIR: './checkpoints/debug'
SAVE_FREQ: 1
SUMMARY_FREQ: 50
MODE: 'train'
# LOADCKPT: './checkpoints/08-19-03-40(original_part_1)/model_000020.ckpt'
# LOADCKPT: './checkpoints/08-20-13-03(original_part_2)/model_000030.ckpt'
# LOADCKPT: './checkpoints/08-27-19-34/model_000018.ckpt'
LOADCKPT: './checkpoints/09-17-16-36/model_000030.ckpt'

TRAIN:
  PATH: '../data/DATAROOT_SCANNET/scannet'
  #PATH: '/scannet/DATAROOT_SCANNET/scannet'
  EPOCHS: 991
  N_VIEWS: 9
  LR: 1e-3
  N_WORKERS: 8
  LREPOCHS: '12,24,48:2'
  APPLY_LOSS: 30
  APPLY_GRU: 20

TEST:
  PATH: '../data/DATAROOT_SCANNET/scannet'
  #PATH: '/scannet/DATAROOT_SCANNET/scannet'
  N_VIEWS: 9
  N_WORKERS: 4

MODEL:
  N_LAYER: 3
  N_VOX: [96, 96, 96]
  VOXEL_SIZE: 0.04
  TRAIN_NUM_SAMPLE: [4096, 16384, 65536]
  TEST_NUM_SAMPLE: [4096, 16384, 65536]

  BACKBONE2D:
    ARC: 'fpn-mnas-1'

  FUSION:
    FUSION_ON: True
    HIDDEN_DIM: 64

    AVERAGE: False
    FULL: True

  RERENDER:
    LOSS: True
    WEIGHT: 10
    MAX_NUM_POINTS: 3000000
    RAYCAST_DEPTH_MAX: 15

  LW: [1.0, 1.0, 1.0]

  THRESHOLDS: [0.0, 0.0, 0.0]
  POS_WEIGHT: 1.5
